{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "성부 성자와 성령",
  "hymnNumber": 3,
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "e30cca48-c275-4d4a-85a2-d513e5819f48",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "성부 성자와 성령",
            "찬송과 영광 돌려보내세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "6c816f37-7c7f-4812-be2b-50fe23bf2a98",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "태초로 지금까지 또 영원무궁토록",
            "성 삼위께 영광 영광 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}