{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "이 천지간 만물들아",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "0eb36834-9c3d-4ae8-aa75-4ebec1f80a09",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "이 천지간 만물들아",
            "복 주시는 주 여호와"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "60d2aee2-cba3-4235-aa13-e60c7843993c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "전능 성부 성자 성령",
            "찬송하고 찬송하세 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}