{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "찬양하라 복되신 구세주 예수",
  "hymnNumber": 31,
  "slides": [
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "d2626693-dff5-4bee-b49b-087b8aefdd6c",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "89e624cc-4b62-4c93-adb6-0a8e0ba149b2",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양하라 복되신 구세주 예수",
            "백성들아 사랑을 전하세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "3ceca7e9-a3e5-42ae-9fe1-f62bea20e963",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "94b9ec0d-4479-48bc-9b63-2c3961315b28",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "경배 하라 하늘의 천군과 천사",
            "주님 앞에 영광을 돌리세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "2f85e73d-8f6e-46bc-9b02-d835ad13baab",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "158ef73f-1fa4-4fa6-83c6-c7843782f2fb",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "목자 같이 우리를 지키시고",
            "종일 품에 늘 안아주시니"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "b83d0a71-7ea9-4b45-b368-5b68bec387ca",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "0baea265-bdaf-4082-836a-4eaa2336486b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양 하라 높으신 권세를 찬양",
            "찬양 찬양 영원히 드리세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "c8fde935-2c0c-4e22-9bf1-3ab7e36be8a2",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "f91e5134-ee6f-47cc-a2cb-09b25a05d024",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양 하라 복되신 구세주 예수",
            "우리 대신 죽임을 당했네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "4c725dec-1cb7-4863-a479-d15fd2d8ddc8",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "7c81d38a-842b-428b-a4fc-1fbd1dc7a04d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "구주 예수 영원한 구원의 소망",
            "경배하며 겸손히 절하세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "4fd8af11-9304-4022-a461-e9c86b058581",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "48af03a9-d7f3-44a9-bffd-6b067835e5bb",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양하라 우리 죄 지신 예수",
            "그의 사랑 한없이 크셔라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "129c407e-c7bc-46a6-9de5-f19d12a0418d",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "290a79b7-5f4f-4f74-8059-7045ac0331c2",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양 하라 높으신 권세를 찬양",
            "찬양 찬양 영원히 드리세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "d91430ec-4fab-4324-beae-75893f50d60a",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 3절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "6e49c23a-5c3e-48ef-aeec-f56f82a3d63d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양하라 복되신 구세주 예수",
            "천사들아 즐겁게 찬양해"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "ba591988-1123-4a24-86f7-351aa3392eed",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 3절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "135e75e2-94cc-457c-9d04-55cfa3e98486",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "구주 예수 영원히 다스리시니",
            "면류관을 주 앞에 드리세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "b583d59e-0253-473c-ad39-76361287851c",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 3절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "b8d9f2e1-7b01-4659-b7d6-715b9020c133",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "구주 예수 세상을 이기시고",
            "영광 중에 또 다시 오시리"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "730c319b-565f-4a1b-ae78-ad88d252cd1a",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 31장 3절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "dd08f31d-4d94-490b-b95d-e65a98039903",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양 하라 높으신 권세를 찬양",
            "찬양 찬양 영원히 드리세 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}