{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "주 예수 이름 높이어",
  "hymnNumber": 37,
  "slides": [
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "4b3b2f4a-042d-4141-856b-1a54473de8b5",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 37장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "7335e242-e27e-4105-9ae0-38bb625a4b4f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 예수 이름 높이어 다 찬양 하여라",
            "다 찬양 하여라 금 면류관을 드려서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "2376d375-d475-4c00-ad8a-e817d919742e",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 37장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "997b7b4c-9311-419e-92b0-c0fa485a9763",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "후렴 : 만유의 주를 찬양하세 찬양",
            "찬양 찬양 만유의 주 찬양 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "92c5c67c-d701-484d-bd21-8d97f21657ed",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 37장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "c38057e1-f296-46b7-b17d-6e93b62d4818",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 예수 당한 고난을 못 잊을 죄인아",
            "못 잊을 죄인아 네 귀한 보배 바쳐서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "699e5082-e6f3-4f96-9b17-6ea5bee29446",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 37장 3절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "b6dd5be6-4181-49bf-a767-6101d64be995",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "이 지구 위에 거하는 온 세상 사람들",
            "온 세상 사람들 그 크신 위엄 높여서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "88ce93de-c6c3-44b5-9332-c0ec9fa52aab",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 37장 4절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "54de61b7-59d6-4d1c-b129-a9d828b54c4b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 믿는 성도 다 함께 주 앞에 엎드려",
            "주 앞에 엎드려 무궁한 노래 불러서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    }
  ]
}