{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "오늘 주신 말씀에",
  "hymnNumber": 57,
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "adce374b-3786-449f-8e00-1b9faed28df0",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "오늘 주신 말씀에 새 힘 얻어서",
            "세상으로 나가서 살아갈 때에"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b44204dd-5473-41d2-aa10-961c3061c814",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "나 혼자 힘으로 늘 부족 하오니",
            "주여 나를 도우사 승리하게 하소서 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}