{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "주가 세상을 다스리니",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "8395af36-47f8-4b2d-a942-23f6fb127e24",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주가 세상을 다스리니 그 위엄이 넘쳐나고",
            "그의 나라와 주의 영광 온 하늘에 가득하다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "27622f33-9664-4f35-b7d1-b8e0729a8255",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "저 흉악한 마귀의 무리 다 멸망케 하시는 주",
            "이 찬양을 주께 드리니 큰 영광을 받으소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "f8fb31a8-e7a6-4fae-ab3c-4b876a84bb3c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주가 권능의 손으로써 이 세상을 창조하니",
            "그의 놀라운 창조솜씨 만 백성이 경탄하네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "dce1dce5-45ff-4703-88ba-939343d15d11",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "저 하늘의 별들도 모두 주 영광을 나타내어",
            "늘 돌보아 주시는 주께 큰 영광을 돌립니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "84444704-9b87-455f-ba5d-5f6118f1f10b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주가 세상의 피조물을 인간에게 다 맡기고",
            "순종하라는 말씀으로 그 권위를 주셨도다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "1833ddab-b342-4b1c-8e6b-43d3f24543fc",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "온 땅 위에 주님의 위엄 늘 넘치며 가득하니",
            "그 나라와 주님의 영광 온 천하게 찬란하다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}