{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "온 천하 만물 우러러",
  "hymnNumber": 69,
  "slides": [
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "73ec679d-079f-43f9-8dee-f856a8952f9f",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "4fab1c94-a310-4954-afd0-732b0f390f12",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "온 천하 만물 우러러 다 주를 찬양하여라",
            "할렐루야 할렐루야 저 금빛 나는 밝은 해"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "dba99830-9d48-47bc-a039-a3fa36c43e70",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "18d4f91f-8683-4e66-924c-ba1e4542eeb9",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "저 은빛 나는 밝은 달 하나님을 찬양하라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "47779687-bc4a-46a7-87cc-959f3e92a2b3",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "0bd781fa-e3cc-4e5b-bd2b-31cb640bcc0f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "후렴 : 할렐루야 할렐루야 할렐루야 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "cd27f839-49ff-48e3-a8b9-2f790bf1abf3",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "b2a0b758-7455-46fd-b0ac-fc98514be2d7",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "힘차게 부는 바람아 떠 가는 묘한 구름아",
            "할렐루야 할렐루야 저 돋는 장한 아침 해"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "6e7711a1-a988-4048-a1ce-aa8f783bbb8c",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "b768773f-7bbd-4ea4-895d-4a347c4dcf11",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "저 지는 고운 저녁 놀 하나님을 찬양하라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "2b4b1652-0ed9-43f5-8041-556b742b1015",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 3절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "4c3b79a8-cbc3-4211-8a97-6f88f9000b52",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "저 흘러가는 맑은 물 다 주를 노래하여라",
            "할렐루야 할렐루야 저 조화 많은 밝은 불"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "31ded48c-1f48-4097-a88b-ecf24330dd6d",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 3절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "4f0623bc-9d03-459c-9a91-ad11da5ab1eb",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "그 빛과 열을 내어서 하나님을 찬양하라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "032c7350-c484-40a2-bf24-14a87f95b225",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 4절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "2482e153-0f79-46d2-a522-67cb34c5cee5",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "저 귀한 땅은 날마다 한없는 복을 펼치어",
            "할렐루야 할렐루야 땅 위의 꽃과 열매들"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "ef4de153-b141-441c-931b-aaf3cefbd738",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 4절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "86dcc4b5-0e64-4b94-ac5e-693b194237c1",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 영광 나타내어서 하나님을 찬양하라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "f4ae8fd2-e134-4937-ada4-16900097f567",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 5절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "c6c4612c-d0ee-47f7-aee1-d66149509f13",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "너 선한 마음 가진 자 늘 용서하며 살아라",
            "할렐루야 할렐루야 큰 고통 슬픔 지닌 자"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "5절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "0d4537ee-b446-47d8-96b7-228530ce33a4",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 5절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "c0f72df4-63ef-4808-b640-d32a396ea578",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "네 근심 주께 맡겨라 하나님을 찬양하라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "7c17e51c-0e4e-4012-98b0-b69e8cea2875",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 6절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "90c7b672-b989-4b87-9502-7e73876a012d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 은혜 받은 만민아 다 꿇어 경배 하여라",
            "할렐루야 할렐루야 성 삼위 일체 주님께"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "6절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "8d219665-b9cc-4699-adf6-63782a0c4789",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 69장 6절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "5c272cd3-012d-49c5-84fb-aec6148a7f4c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "존귀와 영광 돌려라 주를 찬양 할렐루야"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}