{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "샤론의 꽃 예수",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "4c6d8ca9-7609-45e2-800f-8927f84b682d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "샤론의 꽃 예수 나의 마음에 거룩하고 아름답게 피소서",
            "내 생명이 참 사랑의 향기로 간데 마다 풍겨나게 하소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "8d2ac68a-8c7a-46c3-8a87-c57add05a35b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "후렴 : 예수 샤론의 꽃 나의 맘에 사랑으로 피소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "1a98fa76-ee74-44d8-94fc-6c57e6dbe006",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "샤론의 꽃 예수 이 세상에서 어느 꽃과 비교할 수 있으랴",
            "나의 삶에 한결같은 은혜와 사랑으로 가득하게 하소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "2d9289a4-4350-4332-a624-7605eeaf9a1f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "샤론의 꽃 예수 모든 질병을 한이 없는 능력으로 고치사",
            "고통하며 근심하는 자에게 크신 힘과 소망 내려 주소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "a109d5ea-d42b-40e7-9ec5-e28410dad86a",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "샤론의 꽃 예수 길이 피소서 주의 영광 이 땅 위에 가득해",
            "천하 만민 주님 앞에 엎드려 경배 하며 영광 돌릴 때까지"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    }
  ]
}