{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "고요하고 거룩한 밤",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "f9413c1a-5ac9-4294-b435-cdd217a6e75e",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "고요하고 거룩한 밤 구주 예수 나셨다",
            "세상 만민 구원하려 구주 예수 나셨다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "15f8ade4-aa61-4529-ae29-fa4024828bda",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "양을 치는 목자에게 천사들이 하는 말",
            "기쁜 소식 전하노라 구주 예수 나셨다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "4d70d638-cb54-46ba-9e2e-9d51ba9798de",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "별빛 맑게 빛나는 밤 구주 예수 나셨다",
            "길을 잃은 만민 위해 구주 예수 나셨다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "e39d7ec7-bc5a-4c63-b3b0-948deedca88b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "낙타 등에 예물 싣고 별빛 따라 찾아와",
            "동방박사 경배 한다 구주 예수 나셨다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "3be3a542-b40c-4bfc-9869-99c649a7a68a",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리들은 경배 한다 구주 예수 나셨다",
            "천사들은 화답 한다 구주 예수 나셨다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "e6be262c-fefc-4f3e-9843-16401bba5b53",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "약한자의 힘이 되고 외로운 자 벗되어",
            "천한 몸을 입으시고 구주 예수 나셨다 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}