{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "그 고요한 쓸쓸한",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "e8eff8c9-dcf5-4680-a17f-5990ed1e0579",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "그 고요하고 쓸쓸한 저 달빛 아래서",
            "저 하늘 천사 찬양 이 사방에 퍼지네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "bbe9421b-9218-4904-8db4-61efdacace16",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "그 찬란한 빛 비치며 큰 기쁜 소식 들리네",
            "우리 왕 나셨네 주 나셨네 영광 할렐루야"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "6b1d5210-448e-4631-8fb7-240ad4037eb3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "저 볼 것 없는 구유에 주께서 나셨네",
            "그 온유하신 예수님 참 아름다워라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "6e89a456-4c1f-4039-bcf4-ed83c2a203a3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "동방에서 온 박사들 그 귀한 예물 드렸네",
            "우리 왕 나셨네 주 나셨네 영광 할렐루야"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "05080e08-3ddb-491f-aa9f-d4e9e7608dc9",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "온 세상 사는 자녀들 다 기뻐 하여라",
            "그 귀한 아기 예수님 널 위해 나셨다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "8bec74d9-05aa-4169-b69e-d9d4ea76af5b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "참 평화 기쁨 주시는 아기께 경배 하여라",
            "우리 왕 나셨네 주 나셨네 영광 할렐루야"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}