{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "하늘에 찬송이 들리던 그 날",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "0455aa33-9515-4a6f-8d8e-d5243214b07a",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "하늘에 찬송이 들리던 그 날 죄악이 가득한 그날 밤에",
            "동정녀 몸에서 탄생한 주님 우리를 구하러 오신 예수"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "37001bc7-cfe7-487f-bdd0-a274559ad39a",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "살아서 사랑 죽어서 구원 묻혀서 내 죄를 담당하사",
            "부활로 우리를 구하신 예수 다시 오시리 영광의 그 날"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "a3b490f8-995d-4e20-8aba-428cef7638f4",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "갈보리산으로 끌려 가시사 십자가 위에서 죽으신 날",
            "가시관 쓰시고 피 흘리시사 우리를 구하신 구주 예수"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "9ada3f53-0bb3-4d84-8163-6aad2ca58523",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "살아서 사랑 죽어서 구원 묻혀서 내 죄를 담당하사",
            "부활로 우리를 구하신 예수 다시 오시리 영광의 그 날"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "f33bd31b-74cd-438a-93c6-6a66bb680a69",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "동산에 주 홀로 묻히신 그 날 고난을 이기고 쉬신 그 날",
            "천사들 내려와 무덤을 지켜 우리게 소망을 주신 예수"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "61d70353-4d18-4a9e-966b-b993794acc09",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "살아서 사랑 죽어서 구원 묻혀서 내 죄를 담당하사",
            "부활로 우리를 구하신 예수 다시 오시리 영광의 그 날"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "86bad823-5377-41de-8e69-38c379ca58f6",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "무덤이 예수를 못 가둔 그 날 인봉한 그 돌이 굴러간 날",
            "죽음의 권세를 깨뜨린 주님 하늘에 오르신 내주 예수"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "e6f51b3b-186e-4a34-9ede-fb572ad3f3ea",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "살아서 사랑 죽어서 구원 묻혀서 내 죄를 담당하사",
            "부활로 우리를 구하신 예수 다시 오시리 영광의 그 날"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "c83f0c30-e271-4e13-82fd-895f59c8d977",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "천사장 나팔이 울리는 그 날 하늘의 영광이 나타날 때",
            "날 사랑하시는 참되신 친구 날 영접하시러 오실 예수"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "5절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b2bf3057-0686-410f-b107-c71562752041",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "살아서 사랑 죽어서 구원 묻혀서 내 죄를 담당하사",
            "부활로 우리를 구하신 예수 다시 오시리 영광의 그 날"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}