{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "다 함께 찬송 부르자",
  "hymnNumber": 173,
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "79bf3ed6-a210-40ed-8940-a3d77a56c25e",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "다 함께 찬송 부르자 영광의 왕 우리 주 다시 사셨다",
            "할렐루야 다시 사셨다 할렐루야 할렐루야 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}