{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "대속하신 구주께서",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "6e688afd-7d7a-4428-9c19-ded0c28bf550",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "대속하신 구주께서 구름 타고 오실 때",
            "천만 성도 함께 모여 주의 뒤를 따르네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "27686e1d-7c9c-42c7-8ba5-b02d95e1d993",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "할렐루야 할렐루야 우리 구주 오시네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b53896d3-630e-4b55-9f7b-e2b7b0b25484",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "엄숙하신 주의 위풍 모든 사람 뵈올 때",
            "주를 팔고 십자가에 못을 박던 자들이"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "9c0b8312-2520-467a-b8b0-542111b59b16",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "슬피 울고 가슴 치며 참 메시야 뵙겠네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "848b4174-416e-4134-ad03-988c6ecdf3c6",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주가 당한 고난 흔적 모든 사람 볼 때에",
            "구원받은 모든 성도 주께 경배 드리네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "c7fa4e9e-f92d-4c4f-aefa-ec42a99c6edf",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "할렐루야 할렐루야 주님 다시 오시네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "26a65ccd-8850-41a6-9e6b-74976d9ef482",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "고대하던 예수께서 영광중에 오실 때",
            "왕의 왕이 되신 주를 우리 환영 하겠네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "0f8aa957-c4c6-411e-bb04-867b2907d55b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "할렐루야 할렐루야 주여 어서 오소서 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}