{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "비둘기같이 온유한",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "f2bfcc12-ec55-4ac0-afbd-c7e36649a9e3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "비둘기 같이 온유한 은혜의 성령 오셔서",
            "거친 맘 어루만지사 위로와 평화 주소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "28c05287-ea88-4188-bd80-56e8d5a2e138",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "진리의 빛을 비추사 주의 길 바로 걸으며",
            "주님을 옆에 모시고 경건히 살게 하소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "02e4bd9e-33fc-4d05-b7a4-8c6110cb1e87",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주님과 동행하면서 거룩한 길로 행하며",
            "진리의 예수 붙잡고 길 잃지 않게 하소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "4cb63448-fda9-4049-8b63-42ec89dee359",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "연약한 나를 도우사 하나님 나라 이르러",
            "주님의 품에 안기는 영원한 안식 주소서 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    }
  ]
}