{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "나의 사랑하는 책",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "a9982910-ad78-4bc7-ae92-79756615037b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "나의 사랑하는 책 비록 해어졌으나 어머니의 무릎 위에 앉아서",
            "재미있게 듣던 말 그 때 일을 지금도 내가 잊지 않고 기억 합니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "108a80e9-c28f-4e79-825d-e76186bc0f82",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "후렴 : 귀하고 귀하다 우리 어머니가 들려 주시던",
            "재미있게 듣던 말 이 책 중에 있으니 이 성경 심히 사랑 합니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "598ac5eb-8a86-4766-9f8e-41f1ecd2819b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "옛날 용맹스럽던 다니엘의 경험과 유대 임금 다윗 왕의 역사와",
            "주의 선지 엘리야 바람타고 하늘에 올라가던 일을 기억 합니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "f17c7b93-fbef-4b54-b587-8f15539c78a4",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "예수 세상 계실 때 많은 고난 당하고 십자가에 달려 죽임 당한 일",
            "어머니가 읽으며 눈물 많이 흘린 것 지금 까기 내가 기억 합니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b4c4d6ea-b65c-4c74-a9d3-3b63285f2086",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "그 때 일은 지나고 나의 눈에 환하오 어머니의 말씀 기억하면서",
            "나도 시시때때로 성경 말씀 읽으며 주의 뜻을 따라 살려합니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    }
  ]
}