{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "우리를 죄에서 구하시려",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "c7b0c58a-76a2-43bf-a90f-79e67cdca5e6",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리를 죄에서 구하시려 주 예수 십자가 지셨으니",
            "기쁘게 부르세 할렐루야 나 구원 얻었네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "3234ca6f-29d1-40fd-95f7-e16eff3c3cd4",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬송 하세 찬송 하세 주님 나를 구하셨네",
            "찬송 하세 찬송 하세 주가 구원 하셨네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "f474a6d5-f48c-4242-bfdc-676a60b3b106",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리를 주께서 구했으니 이전에 행하던 악한일과",
            "추하고 더러운 모든 죄를 온전히 버렸네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "2eac14c0-0774-473c-b415-b1ab60eacec9",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬송 하세 찬송 하세 주님 나를 구하셨네",
            "찬송 하세 찬송 하세 주가 구원 하셨네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "78d41edf-3232-48cd-aca1-f584ccc930f0",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "나 지금 죄에서 사함 받아 거룩한 백성이 되었으니",
            "이 육신 장막을 벗을 때도 겁날 것 없겠네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "a0e8f61d-34b7-47f8-8ad9-7938b0ee36e6",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬송 하세 찬송 하세 주님 나를 구하셨네",
            "찬송 하세 찬송 하세 주가 구원 하셨네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "03c9413b-74bc-4e1e-b63f-f5769748e40a",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리가 이 세상 떠날 때에 예수의 손목을 굳게 잡고",
            "영원히 즐거운 천국에서 주 함께 살겠네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "618334bb-f6ab-4509-a896-ad57b67d72c7",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬송 하세 찬송 하세 주님 나를 구하셨네",
            "찬송 하세 찬송 하세 주가 구원 하셨네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}