{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "요나처럼 순종않고",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "f66326ee-32b8-47ea-8334-04f03f2ab1d6",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "요나처럼 순종 않고 곁길 갔던 나의 모습",
            "야곱처럼 간사하여 주님 말씀 배반해도"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "c5d85823-1dd1-436d-a81f-46d674b23706",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리 주님 사랑으로 오래도록 참으시고",
            "주님 예수 십자가로 죄인 구원 하시었네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "1b59d2a3-10fe-48b1-be6c-92e9e34b7e46",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "삼손처럼 실패하고 눈물로써 보낸 세월",
            "주님제자 시몬처럼 우리 주를 배반해도"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "390974d4-ae97-4bb9-af75-b67ceefbc9ce",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주님 예수 사랑으로 따스하게 품으시고",
            "주님 예수 은총으로 못난 것을 부르셨네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "f134d68e-2b49-4751-b446-86dc9f89621f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "바울처럼 주님 위해 모든 것을 버리고서",
            "거저주신 은총으로 죽음에서 살았으니"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "2f0796e1-a398-47f7-bb88-607d7c76c2be",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "남은 생애 주의 영광 말씀으로 승리하여",
            "성령님의 인도 따라 온몸으로 섬기리라 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}