{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "속죄하신 구세주를",
  "hymnNumber": 298,
  "slides": [
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "ef0d11a4-d8f0-4533-be8a-c229c0128179",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "ad679933-971c-4025-ada9-c998744ab43d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "속죄하신 구세주를 내가 찬송하리라",
            "내게 자유 주시려고 주가 고난 당했네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "7463e114-cec4-456f-9e94-df9d79007624",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "fb74b5d6-f357-48e4-9fbc-5800fdb91681",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "크신 사랑 찬양하리 나의 죄 사하려고",
            "십자가에 죽임 당한 나의 주 찬양하리(찬양하리)"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "4ab917da-7d88-4234-933f-ea125118c64c",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "be06ae42-adde-47b4-9234-4b0a5694d067",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "내가 구원 받은 증거 기뻐 전파하리라",
            "내 죄 모두 담당 하신 주의 사랑 크셔라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "462d77bd-917d-486f-b00c-c8be312ceb93",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "22c1f35c-edde-4bf5-a30e-3406b075c144",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "크신 사랑 찬양하리 나의 죄 사하려고",
            "십자가에 죽임 당한 나의 주 찬양하리(찬양하리)"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "0b656145-a009-470c-af5c-ff8267d65faa",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 3절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "81fa4cd5-6789-497e-a605-936dde151946",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "승리하신 구세주를 내가 찬송하리라",
            "죄와 죽음 지옥 권세 주가 모두 이겼네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "9c26bab2-31de-4825-b3e8-27e69dbcd3c5",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 3절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "c83a9242-360e-477e-9cca-9bd9066cd506",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "크신 사랑 찬양하리 나의 죄 사하려고",
            "십자가에 죽임 당한 나의 주 찬양하리(찬양하리)"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "b64429b2-5de7-405c-aa81-a643782532c5",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 4절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "dbe097aa-b4ea-44b7-a14d-4cec5dfaf041",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "고마우신 구세주를 내가 찬송하리라",
            "죽음에서 생명으로 나를 인도하셨네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "a706f133-de02-42dc-bd07-999e10b8faec",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 298장 4절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "383ec3aa-0b8b-4df5-80a0-cf35ccaa8947",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "크신 사랑 찬양하리 나의 죄 사하려고",
            "십자가에 죽임 당한 나의 주 찬양하리(찬양하리)"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}