{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "예수 나를 오라 하네",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "2fa0616b-73db-4487-b0ee-28cb274c45cf",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "예수 나를 오라하네 예수 나를 오라하네",
            "어디든지 주를 따라 주와 같이 같이 가려네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "55bb1b38-56a6-4e07-9b50-630dc607814d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "후렴 : 주의 인도하심 따라 주의 인도하심 따라",
            "어디든지 주를 따라 주와 같이 같이 가려네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "f990fcea-d6fb-43ac-a7b5-0b9cbb41eff1",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "겟세마네 동산까지 주와 함께 가려하네",
            "피땀 흘린 동산까지 주와 함께 함께 가려네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "6d43b791-73fb-461e-bddd-67dd4d84450e",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "심판하실 자리까지 주와 함께 가려하네",
            "심판 하실 자리까지 주와 함께 함께 가려네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "dc6537bc-0576-411f-bc8f-91ee8de3d2b3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주가 크신 은혜 내려 나를 항상 돌보시고",
            "크신 영광 보여 주며 나와 함께 함께 가시네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    }
  ]
}