{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "행군 나팔 소리에",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "107f1d25-c472-4ceb-a515-b660c284a31f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "행군 나팔 소리에 주의 호령 났으니",
            "십자가의 군기를 높이 들고 나가세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "dde9902b-67c9-4318-8111-67e7e78ce87d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "선한 싸움 다 싸우고 의의 면류관",
            "의의 면류관 받아 쓰리라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "88913cc6-1804-42cb-9f40-2199a24ea6d5",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "선한 싸움 다 싸우고 의의 면류관 예루살렘 성에서",
            "면류관 받으리 저 요단강 건너"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "91ac67b7-0040-4188-a4ea-75112bd58d73",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리 싸움 마치는 날 의의 면류관 예루살렘 성에서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "f3596c8e-3194-4b20-8420-88c4eaf17bb8",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "악한 마귀 권세를 모두 깨쳐 버리고",
            "승리 하신 주님과 승전가를 부르세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "3f69ba89-bde0-42f8-abef-935dd0015750",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "선한 싸움 다 싸우고 의의 면류관",
            "의의 면류관 받아 쓰리라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "bd378864-abbd-43da-bc91-a84c942ec51b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "선한 싸움 다 싸우고 의의 면류관 예루살렘 성에서",
            "면류관 받으리 저 요단강 건너"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b469aaa6-8b3d-4c74-9b40-b0e84c2d3b78",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리 싸움 마치는 날 의의 면류관 예루살렘 성에서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "bfb3c724-a71b-4eef-bcbd-a5c68bcaa60c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "달려 갈 길 다 가고 싸움 모두 마친 후",
            "주와 함께 기쁨을 용사들아 누리세"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "84f640fe-6ef4-4683-9333-82cf89550e12",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "선한 싸움 다 싸우고 의의 면류관",
            "의의 면류관 받아 쓰리라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "d542fb2d-07f6-4fc7-bb2d-a1cb1c26dac4",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "선한 싸움 다 싸우고 의의 면류관 예루살렘 성에서",
            "면류관 받으리 저 요단강 건너"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "e9cab349-e12d-414f-8dbe-24ec663249bb",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리 싸움 마치는 날 의의 면류관 예루살렘 성에서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}