{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "내가 깊은 곳에서",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "5e935667-4916-4f4c-ae88-68262e4b88ae",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "내가 깊은 곳에서 주를 불러 아뢰니",
            "주여 나의 간구를 들어주심 바라고"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "1ecfe6b1-a82c-42e7-bc98-b59461a0794d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "보좌 앞에 나가니 은혜 내려 주소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "28781f3e-be8f-4292-b274-fc29c3ffbad8",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주가 죄를 살피면 누가 능히 서리요",
            "오직 주만 모든 죄 용서하여 주시니"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "afa97f04-c505-4546-a985-7e36de95ad85",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주님 앞에 떨면서 용서하심 빕니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "6e15941d-072d-40d5-b00d-b0d9fb6a3d72",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "파수꾼이 새벽을 기다리고 바라듯",
            "나의 영혼 주님만 간절하게 바라네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "49c8aaa0-e4e3-496b-844e-6ae95f79548a",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "이스라엘 백성아 주를 바라 보아라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "17b90750-dacf-49a5-b1b8-afc06f8b941a",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주의 크신 은혜와 그의 능력 바라라",
            "주의 깊은 은총에 우리 구원 있으니"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "3f1f309a-b5e7-4b7d-9ba5-bfa4ca0e8694",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "변함없는 주님만 믿고 기다릴지라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}