{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "어두운 내 눈 밝히사",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "f1bbca06-fc5e-40ef-bcc5-81318541f7b3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "어두운 내 눈 밝히사 진리를 보게 하소서",
            "진리의 열쇠 내게 주사 참 빛을 찾게 하소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "0bb70124-0a51-40e9-b816-b6b28e3dbf00",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "깊으신 뜻을 알고자 엎드려 기다리오니",
            "내 눈을 뜨게 하소서 성령이여"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "e4f73dd4-5cf6-4c77-a525-d14c99e52137",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "막혀진 내 귀 여시사 주님의 귀한 음성을",
            "이 귀로 밝히 들을 때에 내 기쁨 한량 없겠네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "1761a807-a54e-45ad-ba68-8967958dff74",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "깊으신 뜻을 알고자 엎드려 기다리오니",
            "내 귀를 열어주소서 성령이여"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "2384d315-87ed-49c5-85ee-f19c4c956e5e",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "봉해진 내 입 여시사 복음을 널리 전하고",
            "차가운 내 맘 녹여주사 사랑을 하게 하소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "054c7ca7-51d9-4a3f-88dd-57cd3fe5e268",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "깊으신 뜻을 알고자 엎드려 기다리오니",
            "내 입을 열어 주소서 성령이여"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}