{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "십자가 그늘 아래",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "b7b84ca3-a945-4477-9166-9e32313ca02f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "십자가 그늘 아래 나 쉬기 원하네",
            "저 햇볕 심히 뜨겁고 또 짐이 무거워"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "ef671779-7427-426f-ac4e-e8766ee6a193",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "이 광야 같은 세상에 늘 방황할 때에",
            "주 십자가의 그늘에 내 쉴 곳 찾았네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "ad23451a-0758-411e-9fa0-d55ace845cdf",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "내 눈을 밝히 떠서 십자가 볼 때",
            "날 위해 고난 당하신 주 예수 보인다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "e56fb83f-dc00-4e9c-b603-30e9c34b1119",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "그 형상 볼 때 내 맘에 큰 찔림 받아서",
            "그 사랑 감당 못하여 눈물만 흘리네"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "ec4cd3f8-b8b0-432b-9a2a-bb9b34898808",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "십자가 그늘에서 나 길이 살겠네",
            "나 사모하는 광채는 주 얼굴 뿐이라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "c6167689-602c-4850-9316-28cfdc89ffe5",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "이 세상 나를 버려도 나 두려움 없네",
            "내 한량없는 영광은 십자가뿐이라 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}