{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "헛된 욕망 길을 가며",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "93d875f7-a8bf-4065-b6e5-f9b2e9104f9f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "헛된 욕망 길을 가며 방황하는 사람아",
            "세상 쾌락 따라 사니 그 생명을 어이해"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "7367d6eb-e526-475f-928f-2fd53746fd30",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "예수 구원 예수 생명 우리 사망 이겼다",
            "영원 생명 주셨으니 그 사랑이 크도다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "eccce706-8640-429f-8fac-23c338c042ca",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "천하 얻고 생명 잃어 유익함이 무언가",
            "세상 권세 헛되도다 어서 주께 나오라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "ac90410d-a053-497d-8f01-c421a8e75a28",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "예수 구원 예수 생명 우리 사망 이겼다",
            "영원 생명 주셨으니 그 사랑이 크도다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "2367d3e4-440a-42ab-bb8b-52137ac76fdf",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "오직 주를 믿은 자가 영생 얻을 것이요",
            "그 영혼이 은혜 입어 평안함을 누리리"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "9bd9edf6-50fb-4aa5-a335-8401b3e88749",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "예수 구원 예수 생명 우리 사망 이겼다",
            "영원 생명 주셨으니 그 사랑이 크도다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}