{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "어서 돌아오오",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "c76ffe62-5eb9-4ddc-b8b8-ac5e9f78507c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "어서 돌아오오 어서 돌아만 오오",
            "지은 죄가 아무리 무겁고 크기로"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "2ea8b832-6be0-4d3d-ba4e-613f17d20045",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 어찌 못 담당하고 못 받으시리요",
            "우리 주의 넓은 가슴은 하늘보다 넓고 넓어"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "0f14c616-8ae4-4e59-8c06-4b82fd06dcc2",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "어서 돌아오오 어서 돌아만 오오",
            "우리 주는 날마다 기다리신다오"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "5743a6bf-935d-4262-b3fe-b3fa0251d17c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "밤마다 문 열어 놓고 마음 졸이시며",
            "나간 자식 돌아오기만 밤새 기다리신다오"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "771ee936-d9a0-43f6-ae70-18ad8511ee13",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "어서 돌아오오 어서 돌아만 오오",
            "채찍 맞아 아파도 주님의 손으로"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "6eac5905-1148-45f8-b8fa-165a0184e492",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "때리시고 어루만져 위로 해 주시는",
            "우리 주의 넓은 품으로 어서 돌아오오 어서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}