{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "사철에 봄바람 불어 잇고",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "87f8629a-120e-428a-af0c-223bef6a1429",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "사철에 봄바람 불어 잇고 하나님 아버지 모셨으니",
            "믿음의 반석도 든든하다 우리집 즐거운 동산이라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "9ce41b56-b132-4ebf-af24-b58470e3ae6b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "고마워라 임마누엘 예수만 섬기는 우리집",
            "고마워라 임마누엘 복되고 즐거운 하루하루"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "fc830831-0799-4622-bc05-1162675e34b0",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "어버이 우리를 고이시고 동기들 사랑에 뭉쳐있고",
            "기쁨과 설움도 같이하니 한간의 초가도 천국이라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "9374e1b2-95e3-47b4-9885-9b9334aa77ac",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "고마워라 임마누엘 예수만 섬기는 우리집",
            "고마워라 임마누엘 복되고 즐거운 하루하루"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "37e640ca-89ca-4892-9ef4-4e44a315c997",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "아침과 저녁에 수고하여 다 같이 일하는 온 식구가",
            "한상에 둘러서 먹고 마셔 여기가 우리의 낙원이라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "eca6a755-d20a-4913-a023-fbf904ab0c90",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "고마워라 임마누엘 예수만 섬기는 우리집",
            "고마워라 임마누엘 복되고 즐거운 하루하루"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}