{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "다정하신 목자 예수",
  "hymnNumber": 567,
  "slides": [
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "9c1fc343-048c-49d6-ad50-e238b6ddf003",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 567장 1절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "c4000bdc-ea91-4d71-8247-9cc9ff39326d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "다정하신 목자 예수 어린 양을 돌보사",
            "캄캄한 밤 지낼 동안 나를 품어 주소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "de171b73-9615-496a-aab0-b4733f6de099",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 567장 2절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "9cada38e-6cc1-4635-b896-157e3e7a7d46",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "선한 목자 내 주 예수 나의 기도 들으사",
            "내일 아침 될 때까지 나를 지켜 주소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "7f17c06c-c407-4f5b-9dc1-4a96c4590582",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 567장 3절"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "fe1ba4cf-0168-4bc4-a6f9-2e0f80b1d2e3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "좋은 옷을 입히시고 맛난 음식 먹이사",
            "고이 길러 주시오니 주여 감사합니다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "verseLabel",
          "id": "86fc886f-5c8f-4325-a9fb-71bc90923170",
          "x": 50.0,
          "y": 4.0,
          "zIndex": 2,
          "lines": [
            "새찬송가 567장 4절 마지막"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 36.0,
          "fontWeight": 600,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "left",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 24.0,
          "height": 8.0
        },
        {
          "type": "text",
          "id": "5cc7ff45-f5e5-4cfe-83fa-e60daf29488c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주여 나의 지난 허물 용서하여 주시고",
            "친구들도 저와 같이 복을 받게 하소서 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    }
  ]
}