{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "주는 나를 기르시는 목자",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "40f202de-1d3a-430d-acde-937ea5f5d844",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주는 나를 기르시는 목자요 나는 주님의 귀한 어린양",
            "푸른 풀밭 맑은 시냇 물가로 나를 늘 인도 하여 주신다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b7013a76-cbe2-4f6c-bb46-cdef9e1354f0",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주는 나의 좋은 목자 나는 그의 어린양",
            "철을 따라 꼴을 먹여 주시니 내게 부족함 전혀 없어라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "dae69286-e599-4ee4-87a8-06d4522683fc",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "예쁜 새들 노래 하는 아침과 노을 비끼는 고운 황혼에",
            "사랑하는 나의 목자 음성이 나를 언제나 불러주신다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "573e04b0-88ba-4660-8b6c-fd22c0b2d51c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주는 나의 좋은 목자 나는 그의 어린양",
            "철을 따라 꼴을 먹여 주시니 내게 부족함 전혀 없어라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "a6389e8a-82d2-40ca-a625-c1cc72e1de9b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "못된 짐승 나를 해치 못하고 거친 비바람 상치 못하리",
            "나의 주님 강한 손을 펼치사 나를 주야로 지켜주신다"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "00281879-7183-4c7b-9036-7dfdbb8faab3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주는 나의 좋은 목자 나는 그의 어린양",
            "철을 따라 꼴을 먹여 주시니 내게 부족함 전혀 없어라 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}