{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "가슴마다 파도친다",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "ce54ad2e-35ed-4a08-9e94-d891d3725ed8",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "가슴마다 파도친다 우리들의 젊은이",
            "눈동자에 어리운다 우리들의 푸른 꿈"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "e3265c48-179c-4bc9-9302-60bc447aa284",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주의 말씀 주의 행함 길과 진리 되시니",
            "우리 평생 한결 같이 주만 따라 살리라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "8aa6eef9-9ec2-4e62-8bfb-d266f4f5af51",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "하늘같이 높푸르자 우리들의 젊은이",
            "바다 같이 넓고 깊자 우리들의 사랑이"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "37bd61f9-7d2d-46b6-b1b1-e18f654d9e9d",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "우리들은 주의 자녀 부름받은 한 형제",
            "몸과 마음 다 받쳐서 주 뜻대로 살리라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "1c03330e-05bd-43c9-93af-d552113cb10c",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "화산같이 타오르자 우리들의 젊은이",
            "폭포같이 줄기차자 우리들의 붉은 피"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "3절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b632d641-5336-43be-bbdc-ced16f8f5021",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "할일 많은 이 나라에 우리 태어났으니",
            "복음 들고 앞장서서 충성되게 일하자"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "8e9f51fa-677a-429a-a6d6-d9ce55c09afb",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "대지같이 광할하자 우리들의 젊은이",
            "산과 같이 우람하자 우리들의 기상이"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "4절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "b61f6e5f-63c8-4e78-ae4a-99d64fa9f9b8",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "십자가를 높이 들고 노래하며 나가자",
            "하늘 뜻이 이 땅 위에 이루어질 때까지 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}