{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "찬양하라 내 영혼아",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "8689731d-6238-4b19-80e1-85ba2b0ec0fa",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "찬양하라 내 영혼아 찬양하라 내 영혼아",
            "온 맘과 정성 다하여 주 찬양하라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "1절"
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "d7dbcf31-3552-432f-a501-99d64975d990",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "경배하라 내 영혼아 경배하라 내 영혼아",
            "온 맘과 정성 다하여 주 경배하라"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ],
      "tag": "2절"
    }
  ]
}