{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "아멘 아멘 아멘 영광과 존귀를",
  "hymnNumber": 628,
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "a1a8df6e-9230-45a8-8904-f629824571b3",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "아멘 아멘 아멘 영광과 존귀를 영원히 주님께",
            "태초부터 영원히 성부와 성자와 성령께"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "5e19ed6a-b249-49e8-8369-d2a2693a2663",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "영광 존귀 찬양 드리세 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}