{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "주여 주여 우리를",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "b5d1a0db-c803-46fb-b6f9-713f91b8879b",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주여 주여 우리를 불쌍히 여기소서",
            "그리스도여 그리스도여 우리를 불쌍히 여기소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "83c11af2-8a8d-4a76-ab10-4ad6a5261495",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주여 주여 우리를 불쌍히 여기소서"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}