{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "주 너를 지키시고",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "f1f13dc8-b38b-4c08-bc6d-f24caa911e2f",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 너를 지키시고 그 얼굴을 네게 돌리시어",
            "참 평화를 참 평화를 그 얼굴을 네게 돌리시어"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "57af5fd6-965e-46f5-8999-40846aab7a05",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "네게 은혜 있으라 주 은혜 그 크신 은혜 네게 있으라",
            "아멘 아멘 아멘 아멘 아멘 아멘 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}