{
  "format": "joowon-subtitle",
  "version": 2,
  "title": "주 함께하소서",
  "slides": [
    {
      "elements": [
        {
          "type": "text",
          "id": "5c013d7c-2dae-4b27-ad25-5424026e8f45",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 함께 하소서 주 함께 하소서",
            "성전을 떠나기 전 주님께 비오니"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    },
    {
      "elements": [
        {
          "type": "text",
          "id": "9b2789e6-b789-4de3-abea-1d92d3e71dcd",
          "x": 50.0,
          "y": 50.0,
          "zIndex": 1,
          "lines": [
            "주 함께 하소서 아멘 아멘 아멘"
          ],
          "anchor": "topLeft",
          "fontFamily": "Noto Sans KR",
          "fontSize": 72.0,
          "fontWeight": 700,
          "color": "#FFFFFF",
          "textShadow": "2.0px 2.0px 8.0px rgba(0,0,204,0.00)",
          "textAlign": "center",
          "textStrokeWidth": 0.0,
          "textStrokeColor": "#000000",
          "shadowEnabled": true,
          "shadowOffsetX": 2.0,
          "shadowOffsetY": 2.0,
          "shadowBlur": 8.0,
          "shadowColor": "#000000CC",
          "width": 85.0,
          "height": 50.0
        }
      ]
    }
  ]
}